### PR TITLE
Publish Microsoft Authored templates to azure samples browser

### PR DESCRIPTION
**Pull request by Menghua1**
Update metadata, and publish `agent-python-openai-prompty-langchain` template to azure samples browser.

@hemarina and @quchuyuan for notification.

### CODE REVIEW

**Comment by v-xuto** [comment]
@quchuyuan Could you review this PR and merge it if it looks good? Thanks a lot.

**Comment by v-xuto** [comment]
@quchuyuan Could you review this PR and merge it if it looks good? Thanks a lot.

**Review by quchuyuan — APPROVED** [review]

**Comment by v-xuto** [comment]
@quchuyuan Could you help merge this PR? Thanks a lot.

**Comment by v-xuto** [comment]
@quchuyuan Could you help merge this PR? Thanks a lot.

**Comment by v-xuto** [comment]
This template has supported in https://github.com/Azure-Samples/agent-python-openai-prompty-langchain/tree/main/docs, so we will close this PR.

**Pull request closed without merging**
